// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Taurus.Infrastructure.Persistence.CompiledModels.Postgres
{
    public partial class PostgresDbContextModel
    {
        private PostgresDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("9d84b2de-9031-468e-b1ec-4a15fa7616eb"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var groupEntityUserEntity = GroupEntityUserEntityEntityType.Create(this);
            var credentialEntity = CredentialEntityEntityType.Create(this);
            var groupEntity = GroupEntityEntityType.Create(this);
            var userEntity = UserEntityEntityType.Create(this);

            GroupEntityUserEntityEntityType.CreateForeignKey1(groupEntityUserEntity, groupEntity);
            GroupEntityUserEntityEntityType.CreateForeignKey2(groupEntityUserEntity, userEntity);
            CredentialEntityEntityType.CreateForeignKey1(credentialEntity, userEntity);

            GroupEntityEntityType.CreateSkipNavigation1(groupEntity, userEntity, groupEntityUserEntity);
            UserEntityEntityType.CreateSkipNavigation1(userEntity, groupEntity, groupEntityUserEntity);

            GroupEntityUserEntityEntityType.CreateAnnotations(groupEntityUserEntity);
            CredentialEntityEntityType.CreateAnnotations(credentialEntity);
            GroupEntityEntityType.CreateAnnotations(groupEntity);
            UserEntityEntityType.CreateAnnotations(userEntity);

            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "10.0.9");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
