// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Taurus.Infrastructure.Persistence;
using Taurus.Infrastructure.Persistence.CompiledModels.Postgres;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(PostgresDbContext), typeof(PostgresDbContextModel))]
