// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Taurus.Infrastructure.Persistence.CompiledModels.Sqlite
{
    public partial class SqliteDbContextModel
    {
        private SqliteDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("c9c85937-1456-47a1-a13a-0acdd4ef93c0"), entityTypeCount: 4)
        {
        }

        partial void Initialize()
        {
            var groupEntityUserEntity = GroupEntityUserEntityEntityType.Create(this);
            var credentialEntity = CredentialEntityEntityType.Create(this);
            var groupEntity = GroupEntityEntityType.Create(this);
            var userEntity = UserEntityEntityType.Create(this);

            GroupEntityUserEntityEntityType.CreateForeignKey1(groupEntityUserEntity, groupEntity);
            GroupEntityUserEntityEntityType.CreateForeignKey2(groupEntityUserEntity, userEntity);
            CredentialEntityEntityType.CreateForeignKey1(credentialEntity, userEntity);

            GroupEntityEntityType.CreateSkipNavigation1(groupEntity, userEntity, groupEntityUserEntity);
            UserEntityEntityType.CreateSkipNavigation1(userEntity, groupEntity, groupEntityUserEntity);

            GroupEntityUserEntityEntityType.CreateAnnotations(groupEntityUserEntity);
            CredentialEntityEntityType.CreateAnnotations(credentialEntity);
            GroupEntityEntityType.CreateAnnotations(groupEntity);
            UserEntityEntityType.CreateAnnotations(userEntity);

            AddAnnotation("ProductVersion", "10.0.9");
        }
    }
}
